[package]
name = "axum-inertia-solid-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
axum-inertia = "0.9"
mime_guess = "2.0.5"
rust-embed = "8.11.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
